FROM node:18.12.1-alpine3.16

LABEL maintainer="We can DO it"
LABEL app="protectator-api"

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build api

RUN npm run test

CMD [ "npm", "start", "enemy" ]
