version: '3'

services:
  postgres:
    image: bitnami/postgresql:14.6.0
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=protectator
    volumes:
      - postgres:/bitnami/postgresql
    ports:
      - 5432:5432

volumes:
  postgres:
